name: Vue3 Vite CI/CD

on:
  push:
    branches:
      - master  # 监听 master 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保 GITHUB_TOKEN 拥有仓库的写入权限

    steps:
      # 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置环境变量，告诉 Vite 当前是在 GitHub Pages 环境中
      - name: Set environment variable for GitHub Pages
        run: echo "VITE_ENV=github" >> $GITHUB_ENV  # 设置 VITE_ENV 为 github

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 使用 Node.js 18 LTS 版本
          cache: 'npm'  # 启用 npm 缓存

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建项目
      - name: Build project
        run: npm run build:h5

      # 可选：部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()  # 仅在构建成功时运行
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/build/h5  # Vue 3 Vite 构建后的输出目录